import { ActivityAuditLog } from "./activity-audit-log.types";

export const activityAuditLogData: ActivityAuditLog[] = [
  {
    id: 1,
    engagementId: "ENG001",
    engagementName: "Onboarding Welcome Email",
    category: "Onboarding & Lifecycle",
    user: "John Doe",
    dateTime: "01/08/2026 09:00",
    action: "Created Engagement",
    previousValue: "-",
    newValue: "Draft",
  },
  {
    id: 2,
    engagementId: "ENG002",
    engagementName: "Dormant Customer Reactivation",
    category: "Transaction Behaviour",
    user: "Sarah Johnson",
    dateTime: "03/08/2026 11:20",
    action: "Updated Execution Type",
    previousValue: "One-Time",
    newValue: "Recurring - Daily",
  },
  {
    id: 3,
    engagementId: "ENG003",
    engagementName: "Account Funding Reminder",
    category: "Transaction Behaviour",
    user: "Michael Brown",
    dateTime: "05/08/2026 14:45",
    action: "Updated Channel",
    previousValue: "Email",
    newValue: "Push Notification → WhatsApp",
  },
  {
    id: 4,
    engagementId: "ENG004",
    engagementName: "KYC Completion Reminder",
    category: "Onboarding & Lifecycle",
    user: "Emily Davis",
    dateTime: "08/08/2026 10:15",
    action: "Changed Status",
    previousValue: "Draft",
    newValue: "Pending Approval",
  },
  {
    id: 5,
    engagementId: "ENG005",
    engagementName: "Currency Conversion Follow-up",
    category: "Transaction Behaviour",
    user: "David Wilson",
    dateTime: "12/08/2026 16:30",
    action: "Updated Frequency Control",
    previousValue: "Once Only",
    newValue: "Once every 30 days",
  },
];
