import type { OnboardingLifecycleEngagement } from "./onboarding-lifecycle.types";

export const onboardingLifecycleData: OnboardingLifecycleEngagement[] = [
  {
    id: 1,
    engagementId: "ENG-2026-00124",
    name: "New Customer Welcome Journey",
    type: "Customer Journey",
    status: "Active",
    owner: "John Kamau",
    priority: "High",
    startDate: "Sep 10, 2026",
    endDate: "",
    nextExecution: "Sep 18, 2026 10:00",
    lastExecution: "Sep 17, 2026 10:00",
    lastUpdated: "Sep 17, 2026 10:24",
  },
  {
    id: 2,
    engagementId: "ENG-2026-00123",
    name: "Dormant GBP → XAF Customers",
    type: "Customer Journey",
    status: "Draft",
    owner: "Mary Wanjiku",
    priority: "Medium",
    startDate: "",
    endDate: "",
    nextExecution: "",
    lastExecution: "",
    lastUpdated: "Sep 17, 2026 09:12",
  },
  {
    id: 3,
    engagementId: "ENG-2026-00122",
    name: "GBP/XAF Rate Alert",
    type: "Event Based",
    status: "Scheduled",
    owner: "David Ochieng",
    priority: "High",
    startDate: "Sep 15, 2026",
    endDate: "",
    nextExecution: "Event Triggered",
    lastExecution: "Sep 16, 2026 14:32",
    lastUpdated: "Sep 16, 2026 14:35",
  },
];